-- access_points_ontario_mnrf.sql
--
-- Generated 2026-04-15 by scripts/fetch-ontario-access-points.js
-- Source: Ontario LIO Open Data — Fishing Access Point layer (MapServer/15)
--
-- One block per Ontario river — wipes prior MNRF rows so re-running
-- swaps in the latest dataset (other submitters preserved).

begin;

-- Grand River — 0 sites within 15mi
delete from public.river_access_points where river_id = 'grand_on' and submitted_by_name = 'Ontario MNRF';

-- Speed River — 1 sites within 15mi
delete from public.river_access_points where river_id = 'speed_on' and submitted_by_name = 'Ontario MNRF';
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('speed_on', 'Shade''s Mills Conservation Area - Boat Launch', 'Private — parking', 'boat_ramp', 'none', 43.37763, -80.28361, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');

-- Eramosa River — 1 sites within 15mi
delete from public.river_access_points where river_id = 'eramosa_on' and submitted_by_name = 'Ontario MNRF';
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('eramosa_on', 'Shade''s Mills Conservation Area - Boat Launch', 'Private — parking', 'boat_ramp', 'none', 43.37763, -80.28361, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');

-- French River — 11 sites within 15mi
delete from public.river_access_points where river_id = 'french_on' and submitted_by_name = 'Ontario MNRF';
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 45.90026, -80.78886, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.20768, -80.55158, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.08087, -80.43144, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.19405, -80.79299, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.08660, -80.34328, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.01987, -80.56850, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Fishing Access Point', 'Unknown', 'boat_ramp', 'none', 46.16388, -80.36368, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Georgian Bay - Key River', 'Private — parking', 'boat_ramp', 'none', 45.89373, -80.56539, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Georgian Bay - Key River', 'Private — parking', 'boat_ramp', 'none', 45.89446, -80.56865, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Wiggle lake', 'Provincial — parking', 'boat_ramp', 'none', 46.23341, -80.56998, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('french_on', 'Trout Lake', 'Provincial', 'boat_ramp', 'gravel', 46.22998, -80.67696, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');

-- Magnetawan River — 11 sites within 15mi
delete from public.river_access_points where river_id = 'magnetawan_on' and submitted_by_name = 'Ontario MNRF';
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Georgian Bay - Key River', 'Private — parking', 'boat_ramp', 'none', 45.89373, -80.56539, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Kawigamog Lake - Lost Channel Road', 'Unknown — parking', 'boat_ramp', 'none', 45.89608, -80.31941, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Georgian Bay - Key River', 'Private — parking', 'boat_ramp', 'none', 45.89446, -80.56865, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Harris Lake', 'Provincial — parking', 'boat_ramp', 'none', 45.69053, -80.39805, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Naiscoot Lake', 'Provincial — parking', 'boat_ramp', 'gravel', 45.64375, -80.40067, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Georgian Bay - Bayfield Inlet', 'Private — parking', 'boat_ramp', 'none', 45.62349, -80.50123, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Giroux Lake', 'Provincial — parking', 'boat_ramp', 'none', 45.70765, -80.48587, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Georgian Bay - Bayfield Inlet', 'Private — parking', 'boat_ramp', 'none', 45.62376, -80.49952, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Harris Lake', 'Private — parking', 'boat_ramp', 'none', 45.69736, -80.38296, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Sturgeon Bay Provincial Park', 'Provincial — parking, fee', 'boat_ramp', 'none', 45.62441, -80.41616, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');
insert into public.river_access_points (river_id, name, description, access_type, ramp_surface, lat, lng, submitted_by_name, verified, verification_status, last_verified_at, last_verified_by) values ('magnetawan_on', 'Pointe au Baril', 'Municipal', 'boat_ramp', 'none', 45.59479, -80.37854, 'Ontario MNRF', true, 'verified', now(), 'Ontario LIO Fishing Access Point dataset');

commit;