import type { AccessPoint, RiverSection } from '@/components/maps/RiverMap'

// Apple River — geometry from USGS NHDPlus HR
// 14 points, simplified at ~5.0m tolerance
// Generated by scripts/extract_phase2.py — do not hand-edit;
// re-run the script if the data needs refreshing.

export const accessPoints: AccessPoint[] = []

export const sections: RiverSection[] = []

export const riverPath: [number, number][] = [
  [-90.4993, 44.1352],
  [-90.4968, 44.1352],
  [-90.4966, 44.1351],
  [-90.4966, 44.1347],
  [-90.4965, 44.1347],
  [-90.4916, 44.1342],
  [-90.4882, 44.1343],
  [-90.4852, 44.1335],
  [-90.4842, 44.1332],
  [-90.4830, 44.1331],
  [-90.4809, 44.1332],
  [-90.4784, 44.1327],
  [-90.4773, 44.1320],
  [-90.4763, 44.1311],
]
