import type { AccessPoint, RiverSection } from '@/components/maps/RiverMap'

// Tangipahoa River — geometry from USGS NHDPlus HR
// 8 points, simplified at ~5.0m tolerance
// Generated by scripts/extract_phase2.py — do not hand-edit;
// re-run the script if the data needs refreshing.

export const accessPoints: AccessPoint[] = []

export const sections: RiverSection[] = []

export const riverPath: [number, number][] = [
  [-90.2768, 30.3367],
  [-90.2761, 30.3367],
  [-90.2746, 30.3364],
  [-90.2727, 30.3358],
  [-90.2717, 30.3353],
  [-90.2593, 30.3269],
  [-90.2281, 30.2872],
  [-90.1964, 30.2796],
]
