import type { AccessPoint, RiverSection } from '@/components/maps/RiverMap'

// Wailua River — geometry from USGS NHDPlus HR
// 20 points, simplified at ~5.0m tolerance
// Generated by scripts/extract_phase2.py — do not hand-edit;
// re-run the script if the data needs refreshing.

export const accessPoints: AccessPoint[] = []

export const sections: RiverSection[] = []

export const riverPath: [number, number][] = [
  [-159.3606, 22.0418],
  [-159.3600, 22.0426],
  [-159.3597, 22.0437],
  [-159.3588, 22.0448],
  [-159.3578, 22.0454],
  [-159.3567, 22.0452],
  [-159.3540, 22.0440],
  [-159.3533, 22.0440],
  [-159.3521, 22.0442],
  [-159.3514, 22.0447],
  [-159.3505, 22.0461],
  [-159.3499, 22.0473],
  [-159.3495, 22.0478],
  [-159.3485, 22.0483],
  [-159.3470, 22.0488],
  [-159.3451, 22.0493],
  [-159.3443, 22.0493],
  [-159.3395, 22.0472],
  [-159.3364, 22.0450],
  [-159.3358, 22.0448],
]
