#!/usr/bin/env python3
"""
Extract a single river's flowline from NHDPlus HR and write a
TypeScript data file in the format components/maps/RiverMap.tsx
expects.

Usage:
    python scripts/extract_river.py \
        --slug manistee \
        --gnis "Manistee River" \
        --gdb "C:/Users/Alaney/Desktop/nhdplus-work/NHDPLUS_H_0406_HU4_GDB.gdb" \
        --simplify 5 \
        --out data/river-maps/manistee.ts

The --gdb path should point to the .gdb folder (an Esri File
Geodatabase). NHDPlus HR ships one per HUC4 watershed.

Dependencies: pip install geopandas fiona shapely pyproj
"""

import argparse
import sys
from pathlib import Path

try:
    import geopandas as gpd
    from shapely.geometry import LineString, MultiLineString
    from shapely.ops import linemerge
except ImportError:
    print("ERROR: geopandas not installed. Run:")
    print("  pip install geopandas fiona shapely pyproj")
    print("Or use conda:")
    print("  conda install -c conda-forge geopandas fiona shapely pyproj")
    sys.exit(1)


def extract(slug: str, gnis: str, gdb: str, simplify_m: float,
            out_path: str) -> bool:
    """
    Extract a river from NHDPlus HR and write a .ts file.
    Returns True on success, False on failure.
    """
    print(f"  [{slug}] reading NHDFlowline from {Path(gdb).name}")

    try:
        gdf = gpd.read_file(gdb, layer="NHDFlowline")
    except Exception as e:
        print(f"  [{slug}] FAIL: could not open GDB: {e}")
        return False

    # Filter by GNIS name (case-insensitive contains match so
    # "Cache La Poudre River" matches "Cache la Poudre River").
    mask = gdf["GNIS_Name"].str.lower().fillna("") == gnis.lower()
    matches = gdf[mask]
    print(f"  [{slug}] {len(matches)} flowlines match GNIS_Name='{gnis}'")

    if len(matches) == 0:
        # Try a contains match for partial names like "Dry Fork"
        # that might appear as "Dry Fork of Cheat River" in NHD.
        mask2 = gdf["GNIS_Name"].str.lower().fillna("").str.contains(
            gnis.lower().split(" river")[0].split(" creek")[0].strip(),
            regex=False,
        )
        matches2 = gdf[mask2]
        if len(matches2) > 0:
            print(f"  [{slug}] partial match found: {len(matches2)} flowlines")
            # Show unique names so the user can refine
            names = matches2["GNIS_Name"].dropna().unique()[:5]
            print(f"  [{slug}] candidate names: {list(names)}")
            matches = matches2
        else:
            print(f"  [{slug}] FAIL: no flowlines matched")
            return False

    # Reproject to WGS84
    if matches.crs and matches.crs.to_epsg() != 4326:
        matches = matches.to_crs("EPSG:4326")

    # Dissolve all matching reaches into one geometry, merge
    # connected lines.
    dissolved = matches.unary_union
    if isinstance(dissolved, LineString):
        merged = dissolved
    elif isinstance(dissolved, MultiLineString):
        merged = linemerge(dissolved)
    else:
        print(f"  [{slug}] FAIL: unexpected geometry type: {type(dissolved)}")
        return False

    # If linemerge couldn't fully connect (gaps around reservoirs),
    # take the longest piece.
    if isinstance(merged, MultiLineString):
        lines = sorted(merged.geoms, key=lambda g: g.length, reverse=True)
        print(f"  [{slug}] {len(lines)} disjoint pieces, taking longest")
        merged = lines[0]

    # Simplify with Douglas-Peucker. Tolerance is in degrees
    # (~0.00001 deg ≈ 1m at mid-latitudes).
    tolerance_deg = simplify_m * 0.00001
    simplified = merged.simplify(tolerance_deg, preserve_topology=False)
    orig = len(merged.coords)
    final = len(simplified.coords)
    print(f"  [{slug}] simplified {orig} -> {final} points")

    if final < 3:
        print(f"  [{slug}] FAIL: too few points after simplification")
        return False

    # Build the TypeScript file
    coords = list(simplified.coords)
    ts_lines = [f"  [{lng:.4f}, {lat:.4f}]," for lng, lat in coords]
    ts_content = (
        "import type { AccessPoint, RiverSection } from '@/components/maps/RiverMap'\n"
        "\n"
        f"// {gnis} — geometry from USGS NHDPlus HR\n"
        f"// {final} points, simplified at ~{simplify_m}m tolerance\n"
        f"// Source GDB: {Path(gdb).name}\n"
        "// Generated by scripts/extract_river.py — do not hand-edit;\n"
        "// re-run the script if the data needs refreshing.\n"
        "\n"
        "export const accessPoints: AccessPoint[] = []\n"
        "\n"
        "export const sections: RiverSection[] = []\n"
        "\n"
        "export const riverPath: [number, number][] = [\n"
        + "\n".join(ts_lines)
        + "\n]\n"
    )

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ts_content, encoding="utf-8")
    size_kb = out.stat().st_size / 1024
    print(f"  [{slug}] wrote {out} ({final} pts, {size_kb:.1f} KB)")
    return True


def main():
    p = argparse.ArgumentParser(description="Extract a river from NHDPlus HR")
    p.add_argument("--slug", required=True, help="RiverScout river id")
    p.add_argument("--gnis", required=True, help="GNIS_Name field value")
    p.add_argument("--gdb", required=True, help="Path to .gdb folder")
    p.add_argument("--simplify", type=float, default=5.0,
                   help="Douglas-Peucker tolerance in meters (default: 5)")
    p.add_argument("--out", required=True, help="Output .ts file path")
    args = p.parse_args()

    ok = extract(args.slug, args.gnis, args.gdb, args.simplify, args.out)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
