#!/usr/bin/env python3
"""
Batch river map extraction from NHDPlus HR.

Reads scripts/river_extraction_map.csv, groups rivers by HUC4,
and extracts every river that doesn't already have a .ts file in
data/river-maps/. Opens each GDB once per HUC4 (they're ~1 GB
each so re-opening per river would be painfully slow), extracts
all rivers for that HUC4 in one pass, and writes the .ts files.

Before extraction, prints a download list of every HUC4 that's
referenced in the CSV but doesn't have a GDB in the work folder.

Usage:
    python scripts/extract_all.py \
        --gdb-root C:/Users/Alaney/Desktop/nhdplus-work \
        --simplify 5

Options:
    --only slug1 slug2 ...    Only extract these rivers (default: all)
    --force                   Re-extract even if the .ts file exists
    --simplify N              Douglas-Peucker tolerance in meters (default: 5)
    --csv PATH                Path to the CSV (default: scripts/river_extraction_map.csv)
    --gdb-root PATH           Folder containing NHDPLUS_H_{HUC4}_HU4_GDB/ subfolders

Dependencies: pip install geopandas fiona shapely pyproj
"""

import argparse
import csv
import sys
import time
from pathlib import Path
from collections import defaultdict

try:
    import geopandas as gpd
    from shapely.geometry import LineString, MultiLineString
    from shapely.ops import linemerge
except ImportError:
    print("ERROR: geopandas not installed. Run:")
    print("  pip install geopandas fiona shapely pyproj")
    sys.exit(1)


def find_gdb(gdb_root: Path, huc4: str) -> Path | None:
    """
    Find the .gdb folder for a HUC4. NHDPlus downloads unzip into
    various folder structures depending on how you unzipped. We
    check common patterns.
    """
    candidates = [
        gdb_root / f"NHDPLUS_H_{huc4}_HU4_GDB" / f"NHDPLUS_H_{huc4}_HU4_GDB.gdb",
        gdb_root / f"NHDPLUS_H_{huc4}_HU4_GDB.gdb",
        gdb_root / f"NHDPLUS_H_{huc4}_HU4_GDB" / "NHDPLUS_H" / f"NHDPLUS_H_{huc4}_HU4_GDB.gdb",
        gdb_root / huc4 / f"NHDPLUS_H_{huc4}_HU4_GDB.gdb",
    ]
    for c in candidates:
        if c.exists():
            return c
    # Glob fallback
    matches = list(gdb_root.rglob(f"NHDPLUS_H_{huc4}*.gdb"))
    return matches[0] if matches else None


def extract_from_gdf(slug: str, gnis: str, gdf: gpd.GeoDataFrame,
                     simplify_m: float, out_path: str) -> bool:
    """
    Extract a single river from an already-loaded GeoDataFrame.
    """
    # Exact match first
    mask = gdf["GNIS_Name"].str.lower().fillna("") == gnis.lower()
    matches = gdf[mask]

    if len(matches) == 0:
        # Partial match fallback
        stem = gnis.lower().split(" river")[0].split(" creek")[0].strip()
        if len(stem) >= 3:
            mask2 = gdf["GNIS_Name"].str.lower().fillna("").str.contains(stem, regex=False)
            matches = gdf[mask2]
            if len(matches) > 0:
                names = matches["GNIS_Name"].dropna().unique()[:5]
                print(f"    partial match ({len(matches)} lines): {list(names)}")

    if len(matches) == 0:
        return False

    # Reproject to WGS84
    if matches.crs and matches.crs.to_epsg() != 4326:
        matches = matches.to_crs("EPSG:4326")

    # Dissolve + merge
    dissolved = matches.unary_union
    if isinstance(dissolved, LineString):
        merged = dissolved
    elif isinstance(dissolved, MultiLineString):
        merged = linemerge(dissolved)
        if isinstance(merged, MultiLineString):
            lines = sorted(merged.geoms, key=lambda g: g.length, reverse=True)
            merged = lines[0]
    else:
        return False

    # Simplify
    tolerance_deg = simplify_m * 0.00001
    simplified = merged.simplify(tolerance_deg, preserve_topology=False)
    final = len(simplified.coords)

    if final < 3:
        return False

    # Write .ts file
    coords = list(simplified.coords)
    ts_lines = [f"  [{lng:.4f}, {lat:.4f}]," for lng, lat in coords]
    ts_content = (
        "import type { AccessPoint, RiverSection } from '@/components/maps/RiverMap'\n"
        "\n"
        f"// {gnis} — geometry from USGS NHDPlus HR\n"
        f"// {final} points, simplified at ~{simplify_m}m tolerance\n"
        "// Generated by scripts/extract_all.py — do not hand-edit;\n"
        "// re-run the script if the data needs refreshing.\n"
        "\n"
        "export const accessPoints: AccessPoint[] = []\n"
        "\n"
        "export const sections: RiverSection[] = []\n"
        "\n"
        "export const riverPath: [number, number][] = [\n"
        + "\n".join(ts_lines)
        + "\n]\n"
    )

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ts_content, encoding="utf-8")
    return True


def main():
    p = argparse.ArgumentParser(description="Batch extract river maps from NHDPlus HR")
    p.add_argument("--csv", default="scripts/river_extraction_map.csv",
                   help="Path to the river extraction CSV")
    p.add_argument("--gdb-root", required=True,
                   help="Folder containing NHDPLUS_H_{HUC4}_HU4_GDB/ subfolders")
    p.add_argument("--simplify", type=float, default=5.0,
                   help="Douglas-Peucker tolerance in meters (default: 5)")
    p.add_argument("--only", nargs="*",
                   help="Only extract these river slugs")
    p.add_argument("--force", action="store_true",
                   help="Re-extract even if the .ts file already exists")
    args = p.parse_args()

    gdb_root = Path(args.gdb_root)
    if not gdb_root.exists():
        print(f"ERROR: --gdb-root does not exist: {gdb_root}")
        sys.exit(1)

    # Read CSV
    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}")
        sys.exit(1)

    rows = list(csv.DictReader(open(csv_path, encoding="utf-8")))
    if args.only:
        only_set = set(args.only)
        rows = [r for r in rows if r["slug"] in only_set]

    print(f"=== RiverScout NHDPlus HR Batch Extraction ===")
    print(f"CSV: {csv_path} ({len(rows)} rivers)")
    print(f"GDB root: {gdb_root}")
    print(f"Simplify: {args.simplify}m")
    print()

    # Group by HUC4
    by_huc: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_huc[r["huc4"]].append(r)

    # ── DOWNLOAD LIST ──────────────────────────────────────────
    # Print every HUC4 that's referenced in the CSV but doesn't
    # have a GDB in the work folder.
    missing_gdbs: list[tuple[str, int]] = []
    available_gdbs: dict[str, Path] = {}
    for huc4 in sorted(by_huc.keys()):
        gdb_path = find_gdb(gdb_root, huc4)
        if gdb_path:
            available_gdbs[huc4] = gdb_path
        else:
            missing_gdbs.append((huc4, len(by_huc[huc4])))

    if missing_gdbs:
        print("╔══════════════════════════════════════════════╗")
        print("║  HUC4s THAT NEED TO BE DOWNLOADED           ║")
        print("╚══════════════════════════════════════════════╝")
        print()
        print("Download these ZIP files and unzip into your --gdb-root folder:")
        print()
        for huc4, count in sorted(missing_gdbs, key=lambda x: -x[1]):
            url = f"https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHDPlusHR/Beta/GDB/NHDPLUS_H_{huc4}_HU4_GDB.zip"
            rivers = [r["slug"] for r in by_huc[huc4]]
            print(f"  HUC4 {huc4} ({count} rivers): {', '.join(rivers[:5)}{'...' if count > 5 else ''}")
            print(f"    {url}")
            print()
        total_missing = sum(c for _, c in missing_gdbs)
        total_available = sum(len(by_huc[h]) for h in available_gdbs)
        print(f"  {len(missing_gdbs)} HUC4s missing ({total_missing} rivers)")
        print(f"  {len(available_gdbs)} HUC4s available ({total_available} rivers)")
        print()
    else:
        print("All HUC4 GDBs found. No downloads needed.")
        print()

    if not available_gdbs:
        print("No GDBs available to process. Download the HUC4 archives listed above.")
        sys.exit(0)

    # ── EXTRACTION ─────────────────────────────────────────────
    extracted: list[str] = []
    skipped: list[str] = []
    failed: list[tuple[str, str]] = []
    skipped_no_gdb: list[str] = []

    for huc4, gdb_path in sorted(available_gdbs.items()):
        huc_rivers = by_huc[huc4]
        # Filter out rivers that already have a .ts file (unless --force)
        to_extract = []
        for r in huc_rivers:
            ts_path = Path(f"data/river-maps/{r['slug']}.ts")
            if ts_path.exists() and not args.force:
                skipped.append(r["slug"])
            else:
                to_extract.append(r)

        if not to_extract:
            continue

        print(f"── HUC4 {huc4}: {len(to_extract)} rivers to extract ──")
        print(f"   GDB: {gdb_path}")
        t0 = time.time()

        try:
            gdf = gpd.read_file(str(gdb_path), layer="NHDFlowline")
            print(f"   loaded {len(gdf):,} flowlines in {time.time() - t0:.1f}s")
        except Exception as e:
            print(f"   FAIL: could not read GDB: {e}")
            for r in to_extract:
                failed.append((r["slug"], f"GDB read error: {e}"))
            continue

        for r in to_extract:
            out_path = f"data/river-maps/{r['slug']}.ts"
            ok = extract_from_gdf(
                r["slug"], r["gnis_name"], gdf, args.simplify, out_path
            )
            if ok:
                ts = Path(out_path)
                pts = sum(1 for line in ts.read_text().split("\n") if line.strip().startswith("["))
                print(f"   ✓ {r['slug']}: {pts} points")
                extracted.append(r["slug"])
            else:
                print(f"   ✗ {r['slug']}: GNIS '{r['gnis_name']}' not found")
                failed.append((r["slug"], f"GNIS name not found: {r['gnis_name']}"))

        elapsed = time.time() - t0
        print(f"   done in {elapsed:.1f}s")
        print()

    # Rivers whose HUC4 GDB isn't downloaded
    for huc4 in sorted(set(by_huc.keys()) - set(available_gdbs.keys())):
        for r in by_huc[huc4]:
            ts_path = Path(f"data/river-maps/{r['slug']}.ts")
            if ts_path.exists() and not args.force:
                skipped.append(r["slug"])
            else:
                skipped_no_gdb.append(r["slug"])

    # ── REPORT ─────────────────────────────────────────────────
    print()
    print("╔══════════════════════════════════════════════╗")
    print("║  EXTRACTION REPORT                          ║")
    print("╚══════════════════════════════════════════════╝")
    print()
    print(f"  Extracted:       {len(extracted)}")
    print(f"  Skipped (exist): {len(skipped)}")
    print(f"  Skipped (no GDB):{len(skipped_no_gdb)}")
    print(f"  Failed:          {len(failed)}")
    print()

    if extracted:
        print("  EXTRACTED:")
        for s in sorted(extracted):
            print(f"    ✓ {s}")
        print()

    if failed:
        print("  FAILED (GNIS name not found — check river_extraction_map.csv):")
        for slug, reason in sorted(failed):
            print(f"    ✗ {slug}: {reason}")
        print()

    if skipped_no_gdb:
        print(f"  SKIPPED (HUC4 GDB not downloaded — {len(skipped_no_gdb)} rivers):")
        for s in sorted(skipped_no_gdb)[:20]:
            print(f"    - {s}")
        if len(skipped_no_gdb) > 20:
            print(f"    ... and {len(skipped_no_gdb) - 20} more")
        print()

    # Also need to register new files in data/river-maps/index.ts
    if extracted:
        print("  ⚠ IMPORTANT: newly extracted rivers need to be registered in")
        print("    data/river-maps/index.ts before they'll appear on the site.")
        print("    Run this after extraction to see which ones are missing:")
        print()
        print("    grep -oP \"'\\K[^']+(?=':)\" data/river-maps/index.ts | sort > /tmp/registered.txt")
        print("    ls data/river-maps/*.ts | sed 's|.*/||;s|\\.ts||' | grep -v index | sort > /tmp/files.txt")
        print("    comm -23 /tmp/files.txt /tmp/registered.txt")
        print()


if __name__ == "__main__":
    main()
